name: Generate Documentation

on:
  push:
    branches:
      - main  # замените на имя вашей основной ветки, если она другая

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Generate documentation
      run: |
        doxygen Doxyfile
        mv html docs  # перемещаем сгенерированную документацию в папку docs

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        add: "docs"
        branch: ${{ github.ref }}
        message: "Generated documentation"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
